const palavroes = [
    "buceta",
    "pau",
    "merda",
    "cocô",
    "xixi",
    "cuzão",
    "pinto",
    "cu",
    "viado",
    "sapatão",
    "traveco",
    "gayzinho",
    "preto",
    "macaco",
    "retardado",
    "mongol",
    "aleijado",
    "idiota",
    "estúpido",
    "burro",
    "preguiçoso",
    "feio",
    "gordo",
    "frouxo",
    "puta",
    "vagabunda",
    "prostituta",
    "galinha",
    "cachorra",
    "piranha",
    "safado",
    "tarado",
    "escroto",
    "saco de merda",
    "filho da puta",
    "foda-se",
    "caralho",
    "porra",
    "cacete",
    "foder",
    "gozar",
    "punheta",
    "chupar",
    "rola",
    "corno",
    "viadinho",
    "travecão",
    "arrombado",
    "baitola",
    "bicha",
    "boiola",
    "maricon",
    "paneleiro",
    "trouxa",
    "inútil",
    "imprestável",
    "mercenário",
    "traidor",
    "fdp",
    "pnc",
    "fds",
    "pqp",
    "lixo",
    "imbecil",
    "rolasso",
    "trombadinha",
    "rapariga",
    "jumenta",
    "amo hitler",
    "nazismo",
    "sou incel",
    "bucetuda",
    "roludo"

  ];
  export default palavroes;
